branches:
  except:
  - "/^wip/"
language: android
addons:
  apt:
    packages:
    - realpath
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
  - sys-img-armeabi-v7a-android-26
  - sys-img-armeabi-v7a-android-21
before_install:
- openssl aes-256-cbc -K $encrypted_62fe32c2c100_key -iv $encrypted_62fe32c2c100_iv
  -in travis/keystore.jks.enc -out keystore.jks -d
- |-
  echo -e "keyAlias=ThingEngineKey
  keyPassword=${KEYSTORE_PASSWORD}
  storePassword=${KEYSTORE_PASSWORD}
  storeFile=./keystore.jks" > keystore.properties
install:
- "./download-ndk.sh"
- export ANDROID_NDK_HOME=~/Android/android-ndk-r16b
- "( cd app ; ./download-prebuilt-binaries.sh )"
- echo y | sdkmanager 'cmake;3.6.4111459'
- echo y | sdkmanager 'lldb;3.0'
- export PATH=./node_modules/.bin:$PATH
- nvm install 8
script: "./gradlew assemble"
deploy:
  skip_cleanup: true
  provider: script
  script: 'curl -F "status=2" -F "notify=1" -F "notes=$( git log -1 --pretty=''format:%s''
  )" -F "notes_type=0" -F "ipa=@app/build/outputs/apk/release/app-release.apk" -H
  "X-HockeyAppToken: $HOCKEYAPP_TOKEN" https://rink.hockeyapp.net/api/2/apps/upload'
  on:
    branch: master
notifications:
  slack:
    secure: F2H25W0OQX5GlPif9M1FmJGWtoqHNZTqwSCk/PUleBpgxfPk3qLkyjI2Q7xRtWmFC+iOQXPa/7WHy6/cm2a17co3efzbClnV/+rrKlYYGKhdQ6NBpmqjA2c6zEVyjTtLrSaYrrpKQsPIqEiX0kNcUfs3/wjOrhoMUp9MZ6YjiYte/8V7/zuuh+zhVMe3VuI4qJ1/dXNnAnYmqZC3BBE0sLzF2lGpfNADi98Z1azIBwOK+WRDoqM0laX7hyOrdYFB27sDGOElNyyjTr6sbkwzR+GnNZvKNIzdIrYVGTyFBq9SGTy6eQ6SNZz3gre1nxjfWYwWiobFVYqgYyVta5D9s0AfafOlRhQsA9xDgUB0PSoRPrmhDNsm3cDGYruN8WB9cHLM5WTYB8cTNg2S0c6s8GArAswxjluorVaNeYCGmNcryD6KV/Dv8JldbTVCBkH52uEOyg8mBveSajCC+FWgEwb8NixHHSeM/NzQZCiGSPc/LaQXTCT+laHkqT6a1nhe0rqGzAusxOkrurC/oSd1Wr8XuQLCp89hGjl5PmJCEkWv2bzE/eiLIBTRON5pz0ooHarynbc6aNw1KbA5L+xVcQ0T9oYCEkM1h7rhA2ikoXLD8H1bHBoYGtb6cQPt63iBB6rZPO9GeoVtvW/pOJRoXqvY0UEth0T7OaaFSXdJl18=
