language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
  - sys-img-armeabi-v7a-android-26
  - sys-img-armeabi-v7a-android-21
before_install:
- openssl aes-256-cbc -K $encrypted_62fe32c2c100_key -iv $encrypted_62fe32c2c100_iv
  -in travis/keystore.properties.enc -out keystore.properties -d
- openssl aes-256-cbc -K $encrypted_62fe32c2c100_key -iv $encrypted_62fe32c2c100_iv
  -in travis/keystore.jks.enc -out keystore.jks -d
install:
- "./download-ndk.sh"
- export ANDROID_NDK_HOME=~/Android/android-ndk-r16b
- "( cd app ; ./download-prebuilt-binaries.sh )"
