language: android
addons:
  apt:
    packages:
    - realpath
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
  - sys-img-armeabi-v7a-android-26
  - sys-img-armeabi-v7a-android-21
before_install:
- openssl aes-256-cbc -K $encrypted_62fe32c2c100_key -iv $encrypted_62fe32c2c100_iv
  -in travis/keystore.jks.enc -out keystore.jks -d
- "echo -e \"keyAlias=ThingEngineKey\nkeyPassword=${KEYSTORE_PASSWORD}\nstorePassword=${KEYSTORE_PASSWORD}\nstoreFile=./keystore.jks\" > keystore.properties"
install:
- "./download-ndk.sh"
- export ANDROID_NDK_HOME=~/Android/android-ndk-r16b
- "( cd app ; ./download-prebuilt-binaries.sh )"
- echo y | sdkmanager 'cmake;3.6.4111459'
- echo y | sdkmanager 'lldb;3.0'
- export PATH=./node_modules/.bin:$PATH
- nvm install 8
script: ./gradlew assemble
after_success:
- "curl -F \"status=2\" -F \"notify=1\" -F \"notes=$( git log -1 --pretty='format:%s' )\" -F \"notes_type=0\" -F \"ipa=@app/build/outputs/apk/release/app-release.apk\" -H \"X-HockeyAppToken: $HOCKEYAPP_TOKEN\" https://rink.hockeyapp.net/api/2/apps/upload"
